### PR TITLE
Aldmeri Dominion Fixes 

### PR DESCRIPTION
**Pull request by Gator7778**
- Added steps for better directions
- Added Clarification tips
- Less manual skips
- Removed faction function from an un-needed spot

### CODE REVIEW

**Comment by Hydra9268** [comment]
Did you merge my recent changes into your fork?
https://i.imgur.com/DvLDnMP.jpeg

**Comment by Hydra9268** [comment]
I ask because after a recent merge I found some of my changes missing.

**Comment by Gator7778** [comment]
yes i did only changes in LevelingCommon were in grahtwood

**Comment by Hydra9268** [comment]
Sounds good. I'll be around later today to do the merge.

**Comment by Gator7778** [comment]
i may have found a way to 100% automate everything without any  manual skips except for entering and exiting screens cause i put something in wrong and wound being a working command i never thought of.

**Comment by Hydra9268** [comment]
Can that be deferred until after these updates release? We're so close to completion.

**Comment by Gator7778** [comment]
no no i havent even had a chance to test it or anything so thats not in the upcoming future

**Pull request merged**
