### PR TITLE
Greymoor/Markarth Guides Finished

### PR DESCRIPTION
**Pull request by Gator7778**

### CODE REVIEW

**Comment by Sharlikran** [comment]
@Gator7778 @Hydra9268 Sometimes when I am the only contributor I do not use more specific commit names. If you would like to approve this pull request with the commit names as is that is fine. I can rebase off of master no problem. However, I would like to ask if this could be closed, and I can make a different pull request from my repo. It's no big deal it's mostly just my preference.

**Comment by Gator7778** [comment]
@Sharlikran im new to pull request did i do it right or do i need  to do it a different way

**Comment by Sharlikran** [comment]
@Gator7778 It was more of a question not a criticizing type of thing. I could have worked with it either way. I am just discussing.

Now first thing though, I chose the DLC

image

It says Mararth but it wants me to go to Bangkori

image

My concern with this is ZOS changed a map ID command. It is hard for me to explain cuz I read so much of other authors and I don't know the nomenclature.

So look at it this way. Lets say that there is a command GetMapIdByIndex and you do and it returns a 0 based index where Bangkori is ID 1234 but the API returns 1233 so you have to add one for it to work properly. Then ZOSDanBaston the developer comes along and says, hey that is a bug it should have never been that way. So they add something to the [addoncompatibilityaliases](https://github.com/ESOUIMods/esoui/blob/master/esoui/ingame/addoncompatibilityaliases/pc/addoncompatibilityaliases.lua) so that it doesn't break old code. However, now it no longer returns the proper number at all.

How is the map being determined from what you understand? I prefer using LibMapPins for map information and it has all sorts of corrections to things. I'm not going to add that I'm just saying that depending on what is going on there may be a better solution.

@Gator7778 I am using Only LibGPS and ZGESO at the moment. I am wondering how to get the guide to tell me a coordinate on the current main where I am.

Screenshot_20210323_175354

As you can see I am at a Harrowstorm site.

**Comment by Sharlikran** [comment]
I am using MerTorchbug and it does indicate which guide I selected.

Screenshot_20210323_175906

As shown here though the current step for `ZGV.CurrentStep` shows Bangkori but the parent guide is Markarth.

**Comment by Sharlikran** [comment]
Wait am I just confused as to what the guide does? May I ask if I go to Western Skyrim

image

Do I start with the regular main quests or did you have different intentions? I may not be understanding what is intended and I'm being a noob.

Everything seems to be working perfectly I just expected to be doing the quests by the Wayshrine.

**Comment by Hydra9268** [comment]
Hi, guys. I'll have an appointment tonight, but I should be online in a few hours.

**Comment by Sharlikran** [comment]
I completely understand that the guide may have you do other quests to get the whole Greymoor experience and take you through the whole story, people are really into that. @Hydra9268 I am asking for to better understand things. Enjoy your appointment.

**Comment by Gator7778** [comment]
@Sharlikran i put the prologue in first it does take you through bangkorai after you accept the quest i can remove that if it would be better

**Comment by Sharlikran** [comment]
@Gator7778 Ahhhhhh that is really cool then. So it works perfectly, and I feel it could be uploaded. Are you okay with that Gator . I would like to use the files as I have then for the version change and for Minion so that it show up in Minion correctly. However, as long as you are okay with it then I can do that now.

**Comment by Gator7778** [comment]
@Sharlikran im good with it

**Comment by Sharlikran** [comment]
I would explain how to rebase but if you are new to git it takes a bit to learn. I'm working on some guild tools so I'm a bit short on time. I apologize.

**Comment by Gator7778** [comment]
i learned how to pull request with youtube ill look up because i never even heard of it

**Comment by Sharlikran** [comment]
I have a feeling you are a far better programmer then me. I kind of dabble but I started in 2012 so I just have different idiocentric ways of doing things.

See if you can find how to configure Notepad++ on windows for doing an interactive rabase.

`git rebase -i --onto 933b5361bbe550ad0a498f058b52b919139cf2e5^ 933b5361bbe550ad0a498f058b52b919139cf2e5^
` and `git push -f --set-upstream origin dev-gator` and `git remote add name-of-remote https://github.com/ESOUIMods/ZGESO.git` and `git checkout -B branch-name` to make a new branch from the one you are on. Those would be some things to look at. Using remotes lets you have one fork and gather code from any other fork.

To be honest I also don't make changes to master. I make a branch, unless I know I am working by myself and it doesn't matter. That way the branch can be rebased if there are regressions or typos. Then you can merge but I dislike the merge commit that ends up being part of HEAD and I forget how to do it with or without fast forward. Sometimes I just cherry pick the commits in `gitk` so that it looks how I want it, again just a visual preference kind of thing.

To me it is the lifeblood of git, rebasing a branch.

```
pick 933b536 Skyrim guide announcement
pick 650b1f8 Update Manifest ZGESO.txt
pick 4ebaeb4 Add Skyrim guide Skyrim.lua
pick 7efbf82 Add Skyrim MapData
pick 810e765 Add Map IDs for Skyrim
pick e2f8e71 Add greymoor guide image
pick a464a81 Update Guide credits
pick cc427d5 artaeum_base name=
pick 1227c95 Finalize version info for manifest

# Rebase bc6049c..1227c95 onto cc427d5 (9 commands)
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# However, if you remove everything, the rebase will be aborted.
#
# Note that empty commits are commented out
```

Gives you options to fixup commits, reword them, squash or combine them. The Wiki I linked you from my xEdit project I had MySysGit, that comes with gitbash which I feel is also important when working on a PC.

image

You get a more complete suite of functions. Unless you found something you are more familiar with.

**Comment by Gator7778** [comment]
i dont upload till ive tested it multiple times that way i dont hurt the master but ill take a look into doing branches my goal now is to  adjust Auridon everything is off by 23-38 yards its something ive wanted done since Zenimax broke it when they released Tamriel One and what 2 program are you using for that and as far as programming im new to LUA on eso but its not much different that wow TBH

**Pull request closed without merging**
