### PR TITLE
Greymoor/Markarth Guides by snichols7778

### PR DESCRIPTION
**Pull request by Sharlikran**
- Adds Greymoor Markarth guides
- Updated commit names
- Fixed typo `nam4e=`
- Updated Manifest for Minion

### CODE REVIEW

**Comment by Hydra9268** [comment]
@Sharlikran I've decided to install ESO so that I can review the guide. Mostly surface glance and another set of eyeballs to look it over. I've created a **review** branch for this purpose. After completing the review, I'll merge the review branch into the master branch. 

Could you close this pull request and make another pull request for the review branch?

cc @Gator7778

**Comment by Gator7778** [comment]
@Hydra9268 yes ill do it when i get home from work this afternoon

**Comment by Sharlikran** [comment]
I will leave you guys to it so that there isn't any confusion.

**Comment by Hydra9268** [comment]
@Sharlikran Thanks! Thank you, @Gator7778, for your hard work.  

I got swamped this evening (it's midnight as I write this). I'll review it in a day or two.

**Pull request closed without merging**
