### PR TITLE
Review

### PR DESCRIPTION
**Pull request by Hydra9268**
Updates to the following zones: 
* Auridon
* Glenumbra
* Grahtwood
* Greenshade
* Malabal Tor
* Reaper's March
* Stonefalls
* Summerset
* The Wailing Prison

### CODE REVIEW

**Comment by Hydra9268** [comment]
@Gator7778 Before I merge, am I missing anything else?

**Comment by Gator7778** [comment]
Aldmeri Dominion is only one that is complete im almost done i got 5 zones left and ill be done with all 3 factions

**Comment by Hydra9268** [comment]
@Gator7778 Sounds good. I wanted to frame the update as zone updates and list which zones either received an update to the MapData and|or the Common guide. I am waiting until the "updated" tag falls off the Addon on ESOUI. I'll upload the update where it will appear in the spotlight again.

**Comment by Gator7778** [comment]
i just fixed that spamming 5-15 minutes crap when you finish your faction by adding faction tags to Mages Guild, Fighters Guild, and Main Quest (Prophet quests) ofc i have to test that before i do anything else with it. and i have dont have it in my files yet im setting it to the side until i finish coldharbor with all 3 characters

**Comment by Gator7778** [comment]
i should be done with Daggerfall Covenant today so ill do a pull on that when i finish. or i can wait till i finish with Ebonheart and do them both together however you want me to do it

**Comment by Gator7778** [comment]
or i can wait till i finish with Ebonheart and do them both together

**Comment by Hydra9268** [comment]
@Gator7778 I'm going to release what you posted along with my updates. We can circle back to those in a week or two.

**Comment by Gator7778** [comment]
by that time ill have all 3 toons out of base game

**Pull request merged**
