### PR TITLE
Current Version Version: 575

### PR DESCRIPTION
**Pull request by Sharlikran**

### CODE REVIEW

**Comment by Hydra9268** [comment]
What are your thoughts on the changes Sharlikran?

**Comment by Sharlikran** [comment]
I'm unsure of what you mean. Those changes are what makes the current version that's on ESOUI. This is the version people are using now.

You just asked for a simple pull request.

**Comment by Hydra9268** [comment]
I updated ZGESO.txt to match the current change number. ## Version: 1.4.642

**Comment by Hydra9268** [comment]
Version: 1.4.644

**Pull request merged**
