### PR TITLE
Added Betnikh

### PR DESCRIPTION
**Pull request by Krandor1**
First 2 zones complete for MQO guides.

### CODE REVIEW

**Comment by Hydra9268** [comment]
Hi. I looked over the changes and appears to be preliminary stuff. Does this include a guide?

**Comment by Krandor1** [comment]
Yes.  The MainquestOnly.Lua file is guides for Khanerthi's roost and Stos m'kai

**Comment by Krandor1** [comment]
If you are looking at it on the web it doesn't display all of the mainquestsonly.lui file by default since it is so big (1500 lines) but you can click on "Load Diff" to get it to display.

**Comment by Hydra9268** [comment]
I had a chance to review the raw source between LevelingCommon and MainquestOnly, and it looks good. Let's keep this in a pending state for now. I made the mistake of working on my Summerset revamp in the master branch. I should have created a separate branch for that. In the future, I will do my work in different branch. In the meantime, I continue to work on the Summerset guide revamp until complete, at which point I can then merge your stuff. That should make for an excellent release. I'll also add you to the credits.

**Comment by Krandor1** [comment]
That is fine.  You see what I'm attempting to do here and I've been testing them on a fresh account.  

The good thing is at this point all my work is in the one new .lua file (outside of the edit to ZGESO.txt) so should be no conflicts.  

My plan is to submit pull requests as I finish each zone and then when finished will likely go back for a polish pass for things like new navigation steps and stuff like that.  

Just my attempt at helping contribute to the cause.  Changes will be a lot more profound in future zones but from both a sequential and figuring out best procedure to do this starter zones were best place to start.

**Comment by Hydra9268** [comment]
Sounds good. 👍

**Comment by Hydra9268** [comment]
Thank you for helping make the Addon better!

**Comment by Krandor1** [comment]
You are very welcome.  Love the addon and use it all the time.  Sometimes though I think "it would be nice if there was a guide for x" and so decided it was best to help make that guide and then share it to the community.   I'm helping myself and helping others too so a win, win for all.

**Pull request closed without merging**
